# Generated by Django 5.2.17 on 2026-09-29 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntrepriseApp', '0002_utilisateur_entreprise_gerant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('type_vehicule', models.CharField(choices=[('camionette', 'Camionnette'), ('camionporteur', 'Camion Porteur'), ('semi-remorque', 'Semi-Remorque'), ('fourgon', 'Fourgon')], default='camionette', max_length=50)),
                ('capacite_kg', models.IntegerField()),
                ('disponibilite', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='EntrepriseApp.entreprise')),
            ],
        ),
    ]
